Repository daytonaio/daytona, pull requests merged in 2024-08, with the labels that each got.

#868 fix: inform user if vscode ide is not installed locally (#654)
  pkg/cmd/ide.go
  pkg/ide/vscode.go
Labels: 🙋 Bounty claim

#874 fix: handle the error message for incorrect token
  pkg/api/controllers/gitprovider/gitprovider.go
  pkg/cmd/gitprovider/add.go
Labels: 🙋 Bounty claim

#822 feat: add workspace status check to code and ssh commands #821
  pkg/cmd/workspace/code.go
  pkg/cmd/workspace/ssh.go
  pkg/cmd/workspace/util/workspace.go
Labels: 🙋 Bounty claim

#797 feat: aws codecommit git provider
  README.md
  cmd/daytona/config/const.go
  go.mod
  go.sum
  pkg/gitprovider/aws-codecommit.go
  pkg/gitprovider/aws-codecommit_test.go
  pkg/server/gitproviders/gitprovider.go
  pkg/server/gitproviders/service.go
  pkg/views/gitprovider/select.go
Labels: 🙋 Bounty claim, docs: needs update

#856 fix: allow users to submit the form earlier
  pkg/cmd/server/configure.go
  pkg/views/server/configure.go
Labels: 🙋 Bounty claim

#812 feat: notify users if server ports are taken
  pkg/api/server.go
  pkg/server/headscale/server.go
  pkg/server/registry/service.go
Labels: 🙋 Bounty claim

#902 fix: add check for Docker requirements in Local Container Registry Start
  pkg/server/registry/service.go
Labels: 🙋 Bounty claim

#908 fix: server configuration fails to make directory
  pkg/server/config.go
  pkg/views/server/configure.go
Labels: 🙋 Bounty claim

#873 fix: clone project from commit url
  go.mod
  go.sum
  pkg/api/docs/docs.go
  pkg/api/docs/swagger.json
  pkg/api/docs/swagger.yaml
  pkg/apiclient/README.md
  pkg/apiclient/api/openapi.yaml
  pkg/apiclient/docs/CloneTarget.md
  pkg/apiclient/docs/GitRepository.md
  pkg/apiclient/model_clone_target.go
  pkg/apiclient/model_git_repository.go
  pkg/db/dto/project.go
  pkg/git/service.go
  pkg/gitprovider/aws-codecommit.go
  pkg/gitprovider/azure-devops.go
  pkg/gitprovider/bitbucket.go
  pkg/gitprovider/bitbucketserver.go
  pkg/gitprovider/git_provider.go
  pkg/gitprovider/gitea.go
  pkg/gitprovider/github.go
  pkg/gitprovider/gitlab.go
  pkg/gitprovider/gitness.go
  pkg/gitprovider/gitnessclient/gitness_client.go
  pkg/gitprovider/types.go
  pkg/server/gitproviders/service.go
Labels: 🙋 Bounty claim

#987 fix: update profile name validation to match workspace name
  internal/constants/profile.go
  pkg/views/profile/create.go
Labels: 🙋 Bounty claim

#1003 fix(gitlab): Configure SHA property for static git context
  pkg/gitprovider/gitlab.go
  pkg/gitprovider/gitlab_test.go
Labels: 🙋 Bounty claim

#954 feat: add Create from Sample creation option
  hack/samples/index.json
  pkg/api/controllers/sample/sample.go
  pkg/api/docs/docs.go
  pkg/api/docs/swagger.json
  pkg/api/docs/swagger.yaml
  pkg/api/server.go
  pkg/apiclient/README.md
  pkg/apiclient/api/openapi.yaml
  pkg/apiclient/api_sample.go
  pkg/apiclient/client.go
  pkg/apiclient/docs/Sample.md
  pkg/apiclient/docs/SampleAPI.md
  pkg/apiclient/docs/ServerConfig.md
  pkg/apiclient/model_sample.go
  pkg/apiclient/model_server_config.go
  pkg/cmd/workspace/util/repository_wizard.go
  pkg/sample/sample.go
  pkg/server/defaults.go
  pkg/server/samples.go
  pkg/server/types.go
  pkg/views/server/configure.go
  pkg/views/workspace/selection/provider.go
  pkg/views/workspace/selection/sample.go
  pkg/views/workspace/selection/view.go
Labels: docs: needs update

#1008 fix: update list of supported ides in daytona code and create
  docs/daytona_code.md
  docs/daytona_create.md
  hack/docs/daytona_code.yaml
  hack/docs/daytona_create.yaml
  pkg/cmd/workspace/code.go
  pkg/cmd/workspace/create.go
Labels: 🙋 Bounty claim

#983 feat: add custom installation loader to the install script
  hack/install.sh
Labels: 🙋 Bounty claim
