Repository daytonaio/daytona, pull requests merged in 2024-09, with the labels that each got.

#1026 feat: Support for Webhook events for GitLab/GitLab self-managed prebuilds
  cmd/daytona/config/const.go
  pkg/gitprovider/gitlab.go
Labels: 🙋 Bounty claim

#1004 feat: add code flag to daytona start cmd
  docs/daytona_start.md
  hack/docs/daytona_start.yaml
  pkg/cmd/workspace/create.go
  pkg/cmd/workspace/start.go
  pkg/cmd/workspace/util/workspace.go
  pkg/views/ide/code.go
Labels: 🙋 Bounty claim

#991 feat: add a workspace start prompt in daytona code for stopped projects
  docs/daytona_code.md
  docs/daytona_ssh.md
  hack/docs/daytona_code.yaml
  hack/docs/daytona_ssh.yaml
  pkg/cmd/workspace/code.go
  pkg/cmd/workspace/ssh.go
  pkg/views/ide/start_workspace.go
Labels: 🙋 Bounty claim

#1076 fix: Handling and Logging of Missing Project Config on Repository Creation (#933)
  pkg/api/controllers/projectconfig/project_config.go
Labels: 🙋 Bounty claim

#799 chore(deps): upgrade github.com/charmbracelet/huh from v0.2.3 to v0.3.0
  go.mod
  go.sum
  pkg/cmd/profiledata/env/set.go
  pkg/views/gitprovider/select.go
  pkg/views/ide/view.go
  pkg/views/initial/view.go
  pkg/views/profile/create.go
  pkg/views/server/apikey/create.go
  pkg/views/server/configure.go
  pkg/views/styles.go
  pkg/views/target/set.go
  pkg/views/workspace/create/configuration.go
  pkg/views/workspace/create/summary.go
  pkg/views/workspace/create/view.go
  pkg/views/workspace/selection/build.go
  pkg/views/workspace/selection/prebuild.go
  pkg/views/workspace/selection/project.go
  pkg/views/workspace/selection/projectconfig.go
  pkg/views/workspace/selection/projectrequest.go
  pkg/views/workspace/selection/view.go
Labels: 🙋 Bounty claim, 💰 Rewarded

#1033 feat(ide): add Jupyter Notebook as IDE option
  cmd/daytona/config/const.go
  docs/daytona_code.md
  docs/daytona_create.md
  docs/daytona_ssh.md
  docs/daytona_start.md
  hack/docs/daytona_code.yaml
  hack/docs/daytona_create.yaml
  hack/docs/daytona_ssh.yaml
  hack/docs/daytona_start.yaml
  pkg/cmd/workspace/code.go
  pkg/cmd/workspace/create.go
  pkg/cmd/workspace/ssh.go
  pkg/cmd/workspace/start.go
  pkg/ide/jupyter.go
Labels: 🙋 Bounty claim

#1048 feat: Add support for Bitbucket Webhook events
  cmd/daytona/config/const.go
  go.mod
  go.sum
  pkg/gitprovider/bitbucket.go
  pkg/server/projectconfig/prebuild.go
Labels: 🙋 Bounty claim

#1087 feat(ide): Support for JetBrains Fleet IDE
  cmd/daytona/config/const.go
  docs/daytona_code.md
  docs/daytona_create.md
  hack/docs/daytona_code.yaml
  hack/docs/daytona_create.yaml
  pkg/cmd/ide.go
  pkg/cmd/workspace/code.go
  pkg/ide/fleet.go
Labels: 🙋 Bounty claim, docs: needs update

#1091 fix: Daytona Info Uncommitted Changes Warning on first create (#745)
  go.mod
  go.sum
Labels: 🙋 Bounty claim

#1072 feat: add spinner to workspace start, stop and delete
  pkg/cmd/target/remove.go
  pkg/cmd/workspace/code.go
  pkg/cmd/workspace/delete.go
  pkg/cmd/workspace/start.go
  pkg/cmd/workspace/stop.go
  pkg/cmd/workspacemode/start.go
  pkg/cmd/workspacemode/stop.go
  pkg/views/util/spinner.go
Labels: 🙋 Bounty claim

#1097 feat: Support for Gitea Webhook Prebuilds
  cmd/daytona/config/const.go
  pkg/gitprovider/gitea.go
Labels: 🙋 Bounty claim

#1100 feat: add auto-complete functionality to input fields(#372)
  pkg/api/docs/docs.go
  pkg/api/docs/swagger.json
  pkg/api/docs/swagger.yaml
  pkg/apiclient/api/openapi.yaml
  pkg/apiclient/docs/ProviderProviderTargetProperty.md
  pkg/apiclient/model_provider_provider_target_property.go
  pkg/provider/types.go
  pkg/views/target/set.go
Labels: 🙋 Bounty claim

#1056 refactor: http status code and error in api(daytonaio#934)
  pkg/api/controllers/gitprovider/branches.go
  pkg/api/controllers/gitprovider/context.go
  pkg/api/controllers/gitprovider/gitprovider.go
  pkg/api/controllers/gitprovider/namespaces.go
  pkg/api/controllers/gitprovider/pull_requests.go
  pkg/api/controllers/gitprovider/repositories.go
  pkg/api/controllers/gitprovider/user.go
  pkg/api/controllers/utils.go
  pkg/gitprovider/aws-codecommit.go
  pkg/gitprovider/azure-devops.go
  pkg/gitprovider/bitbucket.go
  pkg/gitprovider/bitbucketserver.go
  pkg/gitprovider/gitea.go
  pkg/gitprovider/github.go
  pkg/gitprovider/gitlab.go
  pkg/gitprovider/gitness.go
  pkg/gitprovider/gitnessclient/gitness_client.go
Labels: 🙋 Bounty claim

#944 feat: support creating multiple projects non-interactively
  docs/daytona_create.md
  docs/daytona_project-config_add.md
  hack/docs/daytona_create.yaml
  hack/docs/daytona_project-config_add.yaml
  pkg/cmd/projectconfig/add.go
  pkg/cmd/workspace/create.go
  pkg/cmd/workspace/util/add_from_config.go
  pkg/cmd/workspace/util/branch_wizard.go
  pkg/cmd/workspace/util/workspace.go
Labels: never stale

#1103 feat: display commits ahead and behind in dtn info
  internal/util/apiclient/conversion/project.go
  pkg/api/docs/docs.go
  pkg/api/docs/swagger.json
  pkg/api/docs/swagger.yaml
  pkg/apiclient/api/openapi.yaml
  pkg/apiclient/docs/GitStatus.md
  pkg/apiclient/model_git_status.go
  pkg/db/dto/project.go
  pkg/git/service.go
  pkg/views/workspace/info/view.go
  pkg/workspace/project/project.go
Labels: 🙋 Bounty claim

#1110 feat: Added support for Azure DevOps Prebuild Webhooks
  cmd/daytona/config/const.go
  pkg/gitprovider/azure-devops.go
Labels: 🙋 Bounty claim
