Repository daytonaio/daytona, pull requests merged in 2024-07, with the labels that each got.

#729 enhancement: frontend validation for duplicate repo entry in tui (#550)
  pkg/cmd/workspace/util/creation_data.go
  pkg/cmd/workspace/util/repository_wizard.go
  pkg/views/workspace/create/view.go
  pkg/views/workspace/selection/namespace.go
  pkg/views/workspace/selection/provider.go
  pkg/views/workspace/selection/repository.go
  pkg/views/workspace/selection/view.go
Labels: 🙋 Bounty claim, 💰 Rewarded

#725 fix: remove presence of leftover data from previous page in TUI (#592)
  pkg/views/workspace/selection/view.go
Labels: 🙋 Bounty claim

#809 fix: update install.sh by removing unnecessary "continue"
  hack/install.sh
Labels: 🙋 Bounty claim

#802 fix: api-key list -o json
  pkg/cmd/apikey/list.go
Labels: 🙋 Bounty claim

#788 fix: narrow the gradient in logo
  pkg/views/initial/view.go
Labels: 🙋 Bounty claim

#814 fix: no TUI for daytona profile use
  docs/daytona.md
  docs/daytona_profile.md
  docs/daytona_use.md
  hack/docs/daytona.yaml
  hack/docs/daytona_profile.yaml
  hack/docs/daytona_use.yaml
  pkg/cmd/profile/profile.go
  pkg/cmd/profile/use.go
Labels: 🙋 Bounty claim

#798 feat: group help menu commands
  internal/util/cmd.go
  pkg/cmd/apikey/api_key.go
  pkg/cmd/cmd.go
  pkg/cmd/containerregistry/containerregistry.go
  pkg/cmd/gitprovider/gitprovider.go
  pkg/cmd/ide.go
  pkg/cmd/ports/forward.go
  pkg/cmd/profile/profile.go
  pkg/cmd/profile/use.go
  pkg/cmd/profiledata/env/env.go
  pkg/cmd/provider/provider.go
  pkg/cmd/server/serve.go
  pkg/cmd/server/server.go
  pkg/cmd/target/target.go
  pkg/cmd/whoami.go
  pkg/cmd/workspace/code.go
  pkg/cmd/workspace/create.go
  pkg/cmd/workspace/delete.go
  pkg/cmd/workspace/info.go
  pkg/cmd/workspace/list.go
  pkg/cmd/workspace/ssh.go
  pkg/cmd/workspace/start.go
  pkg/cmd/workspace/stop.go
  pkg/cmd/workspacemode/forward.go
  pkg/cmd/workspacemode/info.go
  pkg/cmd/workspacemode/start.go
  pkg/cmd/workspacemode/stop.go
  pkg/cmd/workspacemode/workspace_mode.go
Labels: 🙋 Bounty claim

#836 fix: properties missing from server config view
  pkg/views/server/config.go
Labels: 🙋 Bounty claim

#775 fix: wrong regex rules for repo names
  pkg/server/workspaces/create.go
  pkg/workspace/project.go
Labels: 🙋 Bounty claim

#803 feat: added loader for Provider install progress
  pkg/cmd/provider/install.go
  pkg/cmd/workspace/util/repository_wizard.go
  pkg/views/util/spinner.go
Labels: 🙋 Bounty claim

#827 feat: collect telemetry data
  cmd/daytona/config/config.go
  cmd/daytona/main.go
  docs/daytona.md
  docs/daytona_telemetry.md
  docs/daytona_telemetry_disable.md
  docs/daytona_telemetry_enable.md
  go.mod
  go.sum
  hack/docs/daytona.yaml
  hack/docs/daytona_telemetry.yaml
  hack/docs/daytona_telemetry_disable.yaml
  hack/docs/daytona_telemetry_enable.yaml
  internal/cmd.go
  internal/posthog.go
  internal/util/apiclient/api_client.go
  internal/util/workspace.go
  internal/workspace_mode.go
  pkg/agent/agent.go
  pkg/agent/config/config.go
  pkg/agent/tailscale/server.go
  pkg/agent/types.go
  pkg/api/controllers/workspace/create.go
  pkg/api/controllers/workspace/start.go
  pkg/api/controllers/workspace/stop.go
  pkg/api/controllers/workspace/workspace.go
  pkg/api/middlewares/telemetry.go
  pkg/api/server.go
  pkg/cmd/agent/agent.go
  pkg/cmd/cmd.go
  pkg/cmd/server/serve.go
  pkg/cmd/telemetry/disable.go
  pkg/cmd/telemetry/enable.go
  pkg/cmd/telemetry/telemetry.go
  pkg/posthogservice/service.go
  pkg/server/config.go
  pkg/server/defaults.go
  pkg/server/server.go
  pkg/server/workspaces/create.go
  pkg/server/workspaces/get.go
  pkg/server/workspaces/remove.go
  pkg/server/workspaces/service.go
  pkg/server/workspaces/service_test.go
  pkg/server/workspaces/start.go
  pkg/server/workspaces/stop.go
  pkg/telemetry/cli_events.go
  pkg/telemetry/contants.go
  pkg/telemetry/server_events.go
  pkg/telemetry/telemetry.go
  pkg/workspace/project.go
  pkg/workspace/workspace.go
Labels: docs: needs update

#831 fix: missing terminal cursor
  pkg/cmd/workspace/create.go
Labels: 🙋 Bounty claim

#793 feat: show help menu on unknown command
  pkg/cmd/cmd.go
Labels: 🙋 Bounty claim

#801 feat: show active profile on workspace list
  pkg/cmd/workspace/list.go
  pkg/views/common.go
  pkg/views/containerregistry/select.go
  pkg/views/target/select.go
  pkg/views/workspace/list/view.go
  pkg/views/workspace/selection/view.go
Labels: 🙋 Bounty claim

#794 fix: creation of a new profile through <daytona profile>
  pkg/views/profile/create.go
  pkg/views/profile/select.go
Labels: 🙋 Bounty claim

#830 feat: read server logs directly from file
  docs/daytona_server_logs.md
  hack/docs/daytona_server_logs.yaml
  pkg/cmd/server/logs.go
Labels: 🙋 Bounty claim

#838 fix: handle missing log file error in server logs
  docs/daytona_server_logs.md
  hack/docs/daytona_server_logs.yaml
  internal/util/apiclient/websocket_log_reader.go
  internal/util/log_reader.go
  pkg/api/controllers/log/websocket.go
  pkg/cmd/server/logs.go
Labels: 🙋 Bounty claim

#845 fix: quitting the profile TUI results in FATAL_ERR
  pkg/cmd/profile/delete.go
  pkg/cmd/profile/edit.go
  pkg/cmd/profile/use.go
  pkg/views/profile/select.go
Labels: 🙋 Bounty claim

#795 fix: remove save api key option (#748)
  docs/daytona_api-key_generate.md
  hack/docs/daytona_api-key_generate.yaml
  pkg/cmd/apikey/generate.go
  pkg/views/server/apikey/create.go
Labels: 🙋 Bounty claim

#848 bug: create daytona produces unnecessary debug log
  pkg/cmd/agent/agent.go
Labels: 🙋 Bounty claim

#791 Remove duplicate repo validation
  pkg/cmd/workspace/create.go
  pkg/cmd/workspace/util/creation_data.go
  pkg/cmd/workspace/util/repository_wizard.go
  pkg/views/workspace/create/view.go
  pkg/views/workspace/selection/namespace.go
  pkg/views/workspace/selection/provider.go
  pkg/views/workspace/selection/repository.go
  pkg/views/workspace/selection/view.go
Labels: 🙋 Bounty claim

#800 fix: dont throw a error on ctrl-c for <daytona> command (#615)
  pkg/cmd/apikey/revoke.go
  pkg/cmd/cmd.go
  pkg/cmd/containerregistry/delete.go
  pkg/cmd/containerregistry/set.go
  pkg/cmd/provider/install.go
  pkg/cmd/provider/uninstall.go
  pkg/cmd/provider/update.go
  pkg/cmd/target/remove.go
  pkg/cmd/target/set.go
  pkg/cmd/workspace/create.go
  pkg/cmd/workspace/util/repository_wizard.go
  pkg/common/error.go
  pkg/views/containerregistry/select.go
  pkg/views/initial/view.go
  pkg/views/provider/select.go
  pkg/views/server/apikey/select.go
  pkg/views/target/select.go
  pkg/views/workspace/create/configuration.go
Labels: 🙋 Bounty claim
