Repository daytonaio/daytona, pull requests merged in 2024-11, with the labels that each got.

#1311 feat: add zed ide support
  cmd/daytona/config/const.go
  docs/daytona_code.md
  docs/daytona_create.md
  hack/docs/daytona_code.yaml
  hack/docs/daytona_create.yaml
  pkg/cmd/ide.go
  pkg/cmd/workspace/code.go
  pkg/ide/zed.go
Labels: 🙋 Bounty claim

#1195 feat: Add Bitbucket-Server Prebuilds Webhook
  cmd/daytona/config/const.go
  pkg/gitprovider/bitbucketserver.go
  pkg/gitprovider/bitbucketserver_test.go
Labels: 🙋 Bounty claim, never stale

#1304 feat: add server log rotation
  go.mod
  go.sum
  internal/testing/agent/mocks/apiserver.go
  pkg/api/docs/docs.go
  pkg/api/docs/swagger.json
  pkg/api/docs/swagger.yaml
  pkg/apiclient/README.md
  pkg/apiclient/api/openapi.yaml
  pkg/apiclient/docs/LogFileConfig.md
  pkg/apiclient/docs/ServerAPI.md
  pkg/apiclient/docs/ServerConfig.md
  pkg/apiclient/model_log_file_config.go
  pkg/apiclient/model_server_config.go
  pkg/cmd/server/logs.go
  pkg/cmd/server/restart.go
  pkg/cmd/server/server.go
  pkg/server/config.go
  pkg/server/defaults.go
  pkg/server/log.go
  pkg/server/types.go
  pkg/views/server/config.go
  pkg/views/server/configure.go
Labels: never stale
