Repository daytonaio/daytona, pull requests merged in 2024-06, with the labels that each got.

#653 fix 'profile rm' command, #645
  pkg/cmd/profile/delete.go
Labels: 🙋 Bounty claim

#639 fix: stop server before upgrading
  hack/install.sh
Labels: 🙋 Bounty claim

#636 FEAT: Ability to delete multiple workspaces. Issue #378
  pkg/cmd/workspace/delete.go
  pkg/views/workspace/selection/view.go
  pkg/views/workspace/selection/workspace.go
Labels: 🙋 Bounty claim

#667 feat: direct api and headscale access
  go.sum
  internal/cmd/tailscale/connection.go
  internal/util/frpc.go
  pkg/api/controllers/binary/get_daytona.go
  pkg/cmd/server/serve.go
  pkg/docker/create.go
  pkg/docker/create_test.go
  pkg/provider/manager/manager.go
  pkg/provider/types.go
  pkg/server/headscale/config.go
  pkg/server/headscale/connect.go
  pkg/server/server.go
Labels: docs: needs update

#610 feat: add azure devops git provider
  README.md
  cmd/daytona/config/const.go
  go.mod
  go.sum
  pkg/git/service.go
  pkg/gitprovider/azure-devops.go
  pkg/gitprovider/azure-devops_test.go
  pkg/server/gitproviders/service.go
  pkg/views/gitprovider/select.go
Labels: 🙋 Bounty claim, docs: needs update

#691 feat: allow user to override workspace image at creation
  docs/daytona_create.md
  hack/docs/daytona_create.yaml
  pkg/cmd/workspace/create.go
  pkg/cmd/workspace/util/creation_data.go
  pkg/views/workspace/create/build_choice.go
  pkg/views/workspace/create/configuration.go
  pkg/views/workspace/create/summary.go
Labels: docs: needs update

#606 feature: add self hosting support for bitbucket
  README.md
  cmd/daytona/config/const.go
  go.mod
  go.sum
  pkg/gitprovider/bitbucketserver.go
  pkg/gitprovider/bitbucketserver_test.go
  pkg/server/gitproviders/service.go
  pkg/views/gitprovider/select.go
Labels: 🙋 Bounty claim

#708 feat: build projects on the target machine
  go.mod
  go.sum
  hack/project_image/Dockerfile
  internal/constants/get_daytona_script.go
  internal/testing/docker/mocks/api_client.go
  internal/testing/server/workspaces/mocks/provisioner.go
  internal/util/path.go
  pkg/agent/config/config.go
  pkg/builder/detect/detect.go
  pkg/builder/devcontainer.go
  pkg/builder/devcontainer/config.go
  pkg/builder/devcontainer/types.go
  pkg/builder/factory.go
  pkg/cmd/agent/agent.go
  pkg/docker/client.go
  pkg/docker/container_logs.go
  pkg/docker/container_logs_test.go
  pkg/docker/create.go
  pkg/docker/create_devcontainer.go
  pkg/docker/create_image.go
  pkg/docker/create_test.go
  pkg/docker/destroy.go
  pkg/docker/destroy_test.go
  pkg/docker/exec.go
  pkg/docker/exec_test.go
  pkg/docker/info_test.go
  pkg/docker/start.go
  pkg/docker/start_devcontainer.go
  pkg/docker/start_image.go
  pkg/docker/start_test.go
  pkg/docker/stop.go
  pkg/docker/stop_test.go
  pkg/ide/browser.go
  pkg/ide/vscode.go
  pkg/provider/types.go
  pkg/provisioner/create.go
  pkg/provisioner/provisioner.go
  pkg/server/workspaces/create.go
  pkg/server/workspaces/service_test.go
  pkg/ssh/client.go
  pkg/ssh/exec.go
  pkg/ssh/read_file.go
  pkg/ssh/user.go
  pkg/ssh/write_file.go
  pkg/tailscale/exec_cmd.go
  pkg/views/logs/display.go
  pkg/workspace/project.go
  pkg/workspace/workspace.go
Labels: docs: needs update
